issue#35 endpoint update annotation #35
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #121
Opened 2019-12-29 17:23 UTC by berheg

2020-01-02 21:29 UTC, OlkaA commented on src/server/api/routes/annotations.router.js
> +// ENDPOINT: /api/annotations/ :PATCH
Very minor thing.
I think it is better to comment endpoint like this:
// ENDPOINT: /api/annotations/:id :PATCH

2020-01-02 21:31 UTC, OlkaA commented
Endpoint works good. Annotation is updating.
Swagger also works properly with this endpoint.

2020-01-02 21:34 UTC, OlkaA approved these changes

2020-01-03 12:41 UTC, mo3ni approved these changes
well done 👌

2020-01-08 14:24 UTC, bytewiz requested changes
Please check the comment made from Olha and add that one very small thing then it will be approved 👍 🥇 🔥

2020-01-08 14:24 UTC, bytewiz commented on src/server/api/routes/annotations.router.js
> +// ENDPOINT: /api/annotations/ :PATCH
☝️ Agree

2020-01-08 15:47 UTC, bytewiz approved these changes
Looks good to me 👍

2020-01-08 15:47 UTC, merged