Register form component
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #124
Opened 2020-01-03 13:23 UTC by mo3ni

#87  Creating register component 
(Adding functionality in issue #123 (Register (signup) page using firebase Auth)

2020-01-03 22:33 UTC, rakhshanda-rashid requested changes

2020-01-03 22:33 UTC, rakhshanda-rashid commented on src/client/components/Pages/Register/RegisterPage.component.js
> +import RegisterFormLogin from "../../registerFormLogin/registerFormLogin.component";
overall page seems very good.. just minor css changes need to do in RegisterFormLogin component..also it needs to be responsive.when i tried to minimize the page it disappears..

2020-01-04 18:05 UTC, berheg commented on src/client/components/Pages/Register/RegisterPage.component.js
> +            />
I think i would be better if you describe the picture and do not use words like image, picture in the alt

2020-01-04 18:08 UTC, berheg commented on src/client/components/registerFormLogin/registerFormLogin.component.js
> +        <a href="" className={classSignin}>
I am thinking using router and link functionality of react and connect with loginpage

2020-01-04 18:11 UTC, berheg commented on src/client/components/RegisterForm/Register.component.js
> +              click={() => console.log("signed up with google!")}
here we can use the firebase social media sign up where I have used in #101

2020-01-05 18:34 UTC, mo3ni commented on src/client/components/Pages/Register/RegisterPage.component.js
> +import RegisterFormLogin from "../../registerFormLogin/registerFormLogin.component";
It is for desktop preview and for me when I minimize it minimize doesn't disappear; but some how I changed some css to be more responsive.

2020-01-05 18:34 UTC, mo3ni commented on src/client/components/Pages/Register/RegisterPage.component.js
> +            />
ok

2020-01-05 18:35 UTC, mo3ni commented on src/client/components/registerFormLogin/registerFormLogin.component.js
> +        <a href="" className={classSignin}>
I will do it in next step when I assign functional staffs

2020-01-05 18:35 UTC, mo3ni commented on src/client/components/RegisterForm/Register.component.js
> +              click={() => console.log("signed up with google!")}
that will be in next issue

2020-01-05 21:20 UTC, rakhshanda-rashid approved these changes

2020-01-08 14:35 UTC, bytewiz approved these changes
Looks good to me 👍

2020-01-08 14:35 UTC, merged