endpoint to delete annotation
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #127
Opened 2020-01-03 15:19 UTC by mo3ni

#126 endpoint to delete annotation 
#37 Issue endpoint to delete annotation

2020-01-03 18:48 UTC, laila1222 requested changes
There are two things to fix in the swagger file, which I made comments about. 
Path and deleting annotation work 👍

2020-01-03 18:48 UTC, Laila1222 commented on src/server/config/swagger.json
> +  "/annotations/{id}": {
These annotations paths are in wrong place and therefore it is not showing in the swagger documentation site. You just need to move all these parts (annotations/id, annotations, annotations/delete and their content) in the right place. So within the "paths:" and not outside. If you look at it in your code editor, it might be easier to see, where it should go. :)

2020-01-03 18:48 UTC, Laila1222 commented on src/server/config/swagger.json
> +      "responces":{
Typo: responses instead of responces

2020-01-05 18:26 UTC, mo3ni commented on src/server/config/swagger.json
> +      "responces":{
fixed

2020-01-05 18:29 UTC, mo3ni commented on src/server/config/swagger.json
> +  "/annotations/{id}": {
fixed

2020-01-07 10:33 UTC, laila1222 requested changes

2020-01-07 10:33 UTC, Laila1222 commented on src/server/config/swagger.json
> +  },
This still gives me an error, since it's not in the right place. In the following code I only changed the place of the objects of /annotations, /annotations/{id}, /annotations/delete/{annotation_id}, , and then the swagger file works (which I see on localhost:3000/api/documentation) 

> 
{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "AnnotateTheWeb.API",
    "description": "API documentation for the final project",
    "contact": {}
  },
  "host": "",
  "basePath": "/api",
  "schemes": ["http", "https"],
  "paths": {
    "/screenshots/{key}": {
      "get": {
        "tags": ["Screenshot"],
        "summary": "Checks the status of a taken screenshot and returns information about the screenshot if it's ready.",
        "operationId": "Screenshot_CheckStatusOnScreenshot",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "parameters": [
          {
            "name": "key",
            "in": "path",
            "description": "The unique key for the screenshot",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },

    "/screenshots/": {
      "post": {
        "summary": "Create new screenshot",
        "consumes": ["application/json"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "description": "Create screenshot",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["url", "height", "width", "fk_project_id"],
              "properties": {
                "url": {
                  "type": "string"
                },
                "height": {
                  "type": "number"
                },
                "width": {
                  "type": "number"
                },
                "fk_project_id": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "{\"key\":\"[unique key]\"}",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/annotations/{id}": {
      "get": {
        "tags": ["Annotation"],
        "summary": "Check the status of Annotation and return it's value when it is ready",
        "operationId":"Annotation_CheckStatusOnAnnotation",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The unique id for the annotaion",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "/annotations/": {
      "post": {
        "tags": ["Annotations"],
        "summary": "Create new annotation",
        "consumes": ["application/json"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "description": "Create annotation",
            "required": true,
            "schema": {
              "type": "object",
              "required": ["title", "description", "area", "fk_screenshot_id"],
              "properties": {
                "title": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "area": {
                  "type": "object",
                  "format": "object"
                },
                "fk_screenshot_id": {
                  "type": "integer"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation"
          }
        }
      }
    },
    "/annotations/delete/{annotation_id}":{
      "delete" : {
        "tags" :["annotations"],
        "summery": "Delete specific annotation",
        "consumes":["application/json"],
        "parameters":[
          {
            "name": "annotation_id",
            "in":"path",
            "description":" Unique annotation_id",
            "required":true,
            "type":"string"
          }
        ],
        "responces":{
          "200":{
            "description":"successful operation"
          } 
        }
      }
    }
  },
  "definitions": {}
}

>

2020-01-08 10:43 UTC, mo3ni commented on src/server/config/swagger.json
> +  },
I am not sure that is the same for every one ; as for me works in case that I did

2020-01-08 11:28 UTC, Laila1222 commented on src/server/config/swagger.json
> +  },
Sure, then we can just wait another reviewer. Maybe there's just something with my local setup. ;)

2020-01-08 11:28 UTC, laila1222 approved these changes

2020-01-08 14:41 UTC, bytewiz approved these changes
Seems good to me 👍

2020-01-08 14:42 UTC, bytewiz approved these changes
@mo3ni Added a comment you can implement it if you want to 👍

2020-01-08 14:42 UTC, bytewiz commented on src/server/api/controllers/annotations.controller.js
> +.where({annotation_id:annotation_id})
you could shorten this if you want: `.where({ annotation_id })`

2020-01-11 22:08 UTC, merged