#128 Bugfix - Get annotation by id
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #129
Opened 2020-01-03 20:54 UTC by Laila1222

- Commented out moduler lines that throw error
- Modified controller and router for 'getting annotation by id'
- Added comments with the endpoint paths

2020-01-03 21:06 UTC, OlkaA commented
Nice work 👍

2020-01-03 21:06 UTC, OlkaA approved these changes

2020-01-08 14:18 UTC, bytewiz requested changes
Very minor requests looks good 👍 just some out commented code we don't need 🥇

2020-01-08 14:18 UTC, bytewiz commented on src/server/api/controllers/annotations.controller.js
> +      .where({ annotation_id: annotation_id })
You could write this line out as `.where({ annotation_id })` if you want to save space 👍

2020-01-08 14:18 UTC, bytewiz commented on src/server/api/routes/api-router.js
> +// const modulesRouter = require('./modules.router');
Just remove the commented out code :v:

2020-01-08 14:18 UTC, bytewiz commented on src/server/api/routes/api-router.js
> +// router.use('/modules', modulesRouter);
Just remove the commented out code :v:

2020-01-08 16:20 UTC, Laila1222 commented on src/server/api/controllers/annotations.controller.js
> +      .where({ annotation_id: annotation_id })
done

2020-01-08 16:20 UTC, Laila1222 commented on src/server/api/routes/api-router.js
> +// const modulesRouter = require('./modules.router');
done

2020-01-08 16:20 UTC, Laila1222 commented on src/server/api/routes/api-router.js
> +// router.use('/modules', modulesRouter);
done

2020-01-12 09:44 UTC, zkwsk commented
You need to resolve some conflicts.

2020-01-12 11:53 UTC, bytewiz approved these changes
Looks good to me 👍

2020-01-12 12:30 UTC, merged