issue #101 Feature firebase loginpage authenticate
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #130
Opened 2020-01-03 22:53 UTC by berheg

new PR for issue #101 
Unrelated changes are removed
#101

2020-01-08 14:14 UTC, bytewiz requested changes
Looks good 👍 a few very minor comments and suggestions 💯

2020-01-08 14:14 UTC, bytewiz commented on src/client/components/LoginPage/FormButton/FormButton.css
> +button{
Avoid the global tags in css 👍

2020-01-08 14:14 UTC, bytewiz commented on src/client/components/LoginPage/LoginPage.component.js
> +        />:null}
You could write the same thing as this:

```javascript 
    {isLoading &&<Loading />}
          {!isLoading && !user
            ? <FormLogin
            handleChange = {this.handleChange}
            login = {this.login}
            signup = {this.signup}
            onGoogleSignIn = {this.onGoogleSignIn}
            onFacebookSignIn = {this.onFacebookSignIn}
            onTwitterSignIn = {this.onTwitterSignIn} 
          />
         : <FormButton
          title="Log Out"
          buttons="logout-btn"
          click={this.logout}
          logo=""
        />}

```
them you don't have to write `null` that much 👍

2020-01-08 14:14 UTC, bytewiz commented on src/client/components/LoginPage/LoginPage.component.js
> +    auth.signInWithEmailAndPassword(this.state.email, this.state.password).then((u)=>{
`u` is unused and can be removed it seems

2020-01-08 14:14 UTC, bytewiz commented on src/client/components/LoginPage/LoginPage.component.js
> +    }).then((u)=>{console.log(u)})
There is a "double" `.then((u) => ` and you can remove both as they are not used really, remove the log

2020-01-08 14:14 UTC, bytewiz commented on src/client/components/LoginPage/LoginPage.component.js
> +  }
Just an alternative: You could write the entire function like this if you want to use async/await

```javascript
signup = async (e) => {
    try {
        await auth.createUserWithEmailAndPassword(this.state.email, this.state.password)
   } catch((error) => {
        console.log(error);
   })
}
```

2020-01-08 14:14 UTC, bytewiz commented on src/client/components/LoginPage/LoginPage.component.js
> +    }
this is not really doing anything, remove it thanks! 👍

2020-01-08 14:14 UTC, bytewiz commented on src/client/components/LoginPage/LoginPage.component.js
> +   .then((result, error) => {
if we don't handle the error this can be removed too

2020-01-08 14:14 UTC, bytewiz commented on src/client/components/LoginPage/LoginPage.component.js
> +}
this is not really doing anything, remove it thanks! 👍

2020-01-08 14:14 UTC, bytewiz commented on src/client/components/LoginPage/LoginPage.component.js
> +//import app from '../../firebase/configure';
remove this line

2020-01-08 14:14 UTC, bytewiz commented on src/client/components/LoginPage/LoginPage.component.js
> +    });
no need for the `()`

```
this.state = {
      user: null,
      email: '',
      password: '',
      isLoading: false
    };
```

2020-01-08 15:50 UTC, berheg commented on src/client/components/LoginPage/FormButton/FormButton.css
> +button{
fixed

2020-01-08 16:02 UTC, berheg commented on src/client/components/LoginPage/LoginPage.component.js
> +        />:null}
Thank you for your suggestion, but for the case: isLoading true and user: false Loading and Logout button displayed.
I have modified this way: 
---
{isLoading?<Loading />:null}
          {!isLoading && !user &&<FormLogin
            handleChange = {this.handleChange}
            login = {this.login}
            signup = {this.signup}
            onGoogleSignIn = {this.onGoogleSignIn}
            onFacebookSignIn = {this.onFacebookSignIn}
            onTwitterSignIn = {this.onTwitterSignIn} 
          />}
          {user && <FormButton
          title="Log Out"
          buttons="logout-btn"
          click={this.logout}
          logo=""
        />}
---

2020-01-08 16:03 UTC, berheg commented on src/client/components/LoginPage/LoginPage.component.js
> +        />:null}
`{isLoading?<Loading />:null}
          {!isLoading && !user &&<FormLogin
            handleChange = {this.handleChange}
            login = {this.login}
            signup = {this.signup}
            onGoogleSignIn = {this.onGoogleSignIn}
            onFacebookSignIn = {this.onFacebookSignIn}
            onTwitterSignIn = {this.onTwitterSignIn} 
          />}
          {user && <FormButton
          title="Log Out"
          buttons="logout-btn"
          click={this.logout}
          logo=""
        />}`

2020-01-08 16:13 UTC, berheg commented on src/client/components/LoginPage/LoginPage.component.js
> +  }
thank you modified

2020-01-08 16:14 UTC, berheg commented on src/client/components/LoginPage/LoginPage.component.js
> +    }
thanks deleted

2020-01-08 16:15 UTC, berheg commented on src/client/components/LoginPage/LoginPage.component.js
> +}
thanks fixed

2020-01-08 16:16 UTC, berheg commented on src/client/components/LoginPage/LoginPage.component.js
> +    });
thanks fixed

2020-01-08 16:22 UTC, berheg commented on src/client/components/LoginPage/LoginPage.component.js
> +//import app from '../../firebase/configure';
thanks removed

2020-01-08 16:37 UTC, berheg commented on src/client/components/LoginPage/LoginPage.component.js
> +    auth.signInWithEmailAndPassword(this.state.email, this.state.password).then((u)=>{
thanks removed

2020-01-08 16:55 UTC, berheg commented on src/client/components/LoginPage/LoginPage.component.js
> +    }).then((u)=>{console.log(u)})
Thanks removed

2020-01-18 12:42 UTC, Laila1222 commented on webpack.config.js
> +const dotenv = require("dotenv");
Are the changes in these file related to the login page? If not, then I suggest to remove them from this PR. :)

2020-01-18 15:49 UTC, bytewiz commented on webpack.config.js
> +const dotenv = require("dotenv");
@berheg ☝️ Agree with this, please change that unless it is required for login

2020-01-19 09:38 UTC, berheg commented on webpack.config.js
> +const dotenv = require("dotenv");
it is required but i have not modified it. 
is it possible to show up here even if i did not modified it

2020-01-19 15:04 UTC, bytewiz commented
Closing this in favor of #175  (to avoid removing half of the project)

2020-01-19 15:04 UTC, closed without merging