Functioning homepage
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #173
Opened 2020-01-19 14:22 UTC by Laila1222

When typing url and pressing enter:
new project will be created
new screenshot will be created to that project
screenshot_key is saved in context. 

Mobile version functionality is not set up. Issue should be created for that.

2020-01-21 18:22 UTC, JonathanMH requested changes
Hi! Thank you so much for the PR! it looks good overall, I have left a few comments where we should adjust a few things :)

2020-01-21 18:22 UTC, JonathanMH commented on src/client/pages/Home/HomePage.js
> +    this.postData('http://localhost:3000/api/projects/', {
the URL in this request needs to work in production as well, so we can not use the absolute path

2020-01-21 18:22 UTC, JonathanMH commented on src/client/context/AuthContext.js
> +    user_id: '4',
`user_id: 4` will not necessarily be present in the database, but this is fine for now. Let's maybe place a `// TODO` comment or similar to remind us of this one.

maybe it should be user_id: 1, since that's what's in the knex database seed?

2020-01-21 18:22 UTC, JonathanMH commented on src/client/pages/Home/HomePage.js
> +        this.postData('http://localhost:3000/api/screenshots/', {
the url should not contain `http://localhost:3000`

2020-01-21 18:22 UTC, JonathanMH commented on src/client/pages/Home/HomePage.js
> +        this.postData('http://localhost:3000/api/screenshots/', {
the url should not contain `http://localhost:3000`

2020-01-22 08:04 UTC, Laila1222 commented on src/client/pages/Home/HomePage.js
> +    this.postData('http://localhost:3000/api/projects/', {
Done.

2020-01-22 08:04 UTC, Laila1222 commented on src/client/pages/Home/HomePage.js
> +        this.postData('http://localhost:3000/api/screenshots/', {
Done

2020-01-22 08:04 UTC, Laila1222 commented on src/client/pages/Home/HomePage.js
> +        this.postData('http://localhost:3000/api/screenshots/', {
done

2020-01-22 08:04 UTC, Laila1222 commented on src/client/context/AuthContext.js
> +    user_id: '4',
Done

2020-01-22 10:18 UTC, OlkaA approved these changes
Looks good👍.
After inserting URL data goes to db.

But travis fails, need to fix test for component

2020-01-22 17:59 UTC, JonathanMH approved these changes

2020-01-22 18:03 UTC, merged