Issue#28 Added component ToggleButton
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #44
Opened 2019-11-27 19:58 UTC by OlkaA

Added new component ToggleButton with responsive design

2019-11-28 09:48 UTC, laila1222 approved these changes
Looks good. 👍

2019-11-29 09:52 UTC, bytewiz requested changes
Looks good minor comment 👍

2019-11-29 09:52 UTC, bytewiz commented on src/client/stories/index.js
>  storiesOf("Button", module)
Can we remove this please it is no longer needed ✌️

2019-11-29 09:52 UTC, bytewiz commented on src/client/stories/index.js
>  import { Button } from "@storybook/react/demo";
Can we remove this please it is no longer needed ✌️

2019-11-30 09:40 UTC, OlkaA commented on src/client/stories/index.js
>  storiesOf("Button", module)
Done!

2019-12-01 12:55 UTC, bytewiz requested changes

2019-12-01 12:55 UTC, bytewiz commented on src/client/components/ToggleButton/ToggleButton.jsx
> +const ToggleButton = ({ }) => {
@OlkaA As mentioned if you can also expose the `value` for the "switch/toggle button" so we can get the value from outside of the component that will be perfect 👌 so we have a way to figure out which of the options are the selected one 👍

2019-12-02 07:06 UTC, OlkaA commented on src/client/components/ToggleButton/ToggleButton.jsx
> +const ToggleButton = ({ }) => {
Exposed the value fot ToggleButton.
Added test.
Resolved merged conflicts.

2019-12-02 12:54 UTC, zkwsk approved these changes

2019-12-08 11:21 UTC, bytewiz approved these changes
💥 Looks good!

2019-12-08 12:02 UTC, merged