Issue #20-Comment box component  added
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #45
Opened 2019-11-28 11:08 UTC by berheg

I did not include action in the storybook , because it requires additional package dependency. I will update action functionality  after the package is installed in the origin develop. 

#20

2019-11-29 10:09 UTC, bytewiz requested changes
![image](https://user-images.githubusercontent.com/16811871/69860656-ff8c4a80-1296-11ea-91e3-005ea47658a9.png)
Think there is something missing for the styling it doesn't look exactly like #20 

Also always keep components capitalized e.g. change `blogCard.jsx` to `BlogCard.jsx`

2019-11-29 10:09 UTC, bytewiz commented on src/client/components/Container/DropDown/DropDown.Component.jsx
> +const DropDown = props => {
Should this component take a some dynamic props instead of hardcoded items in the dropdown?

e.g. `{props.children}`

2019-11-29 10:09 UTC, bytewiz commented on src/client/components/DotButton/DotButton.Component.jsx
> +const DotButton = props => {
Why is this called `button` when it is an unordered list?  if it is a button please use the correct HTML syntax for that `<button>`

2019-11-29 10:09 UTC, bytewiz commented on src/client/components/DotButton/DotButton.story.js
> +  .add("with text", () => <DotButton title="..."></DotButton>);
The `title` prop is not used in the component, either include it in the component or remove it from here.

2019-11-29 10:09 UTC, bytewiz commented on src/client/components/DropDown/DropDown.Component.jsx
> +        <List  onClick={onClickHandler} title={'...'}/>
This is not gonna work you should pass the `onClickHandler` as a prop

2019-11-29 10:09 UTC, bytewiz commented on src/client/components/DropDown/DropDown.Component.jsx
> +function onClickHandler() {
remove this and expect it as a prop instead

2019-11-29 10:09 UTC, bytewiz commented on src/client/components/DropDown/DropDown.Component.jsx
> +const Anchor = props => {
Also shouldn't you be able to pass in certain list items instead of hardcoding them?

Also why do you have two different dropdown components? 

And why is this one named `Anchor`?

2019-11-29 10:09 UTC, bytewiz commented on src/client/stories/index.js
>  storiesOf("Button", module)
Delete this `Button` story it is not used anymore

2019-11-29 10:09 UTC, bytewiz commented on src/client/stories/index.js
>  import { Button } from "@storybook/react/demo";
remove this import as well

2019-11-29 10:09 UTC, bytewiz commented on src/client/stories/index.js
> +import { from } from "array-flatten";
remove this as well

2019-11-29 10:09 UTC, bytewiz commented on src/client/components/List/List.Component.jsx
> +    <li className={"listComponent"}>{props.title}</li>
Where does the style class for this component come from?

2019-11-29 10:09 UTC, bytewiz commented on src/client/components/Input/Input.Component.jsx
> +const Input = props => {
Should we maybe have a way to handle `submit` when you want to add a comment? for example on pressing the `Enter` key

2019-11-29 13:40 UTC, berheg commented on src/client/components/DotButton/DotButton.story.js
> +  .add("with text", () => <DotButton title="..."></DotButton>);
I have included in the component.

2019-11-29 13:41 UTC, berheg commented on src/client/components/DropDown/DropDown.Component.jsx
> +const Anchor = props => {
I have moved dropdown component to container but it did not delete the other one so i do it manually. So it should be deleted the Anchor component.

2019-11-29 13:45 UTC, berheg commented on src/client/components/DropDown/DropDown.Component.jsx
> +        <List  onClick={onClickHandler} title={'...'}/>
I have deleted functions because it requires additional package in the package json file.

2019-11-29 13:49 UTC, berheg commented on src/client/components/List/List.Component.jsx
> +    <li className={"listComponent"}>{props.title}</li>
From the parent  blogCard.css

2019-11-29 14:00 UTC, berheg commented on src/client/stories/index.js
> +import { from } from "array-flatten";
In study group we agree to do story for each component

2019-12-01 12:57 UTC, bytewiz commented on src/client/stories/index.js
> +import { from } from "array-flatten";
Ah it is just this line that is not used: `import { from } from "array-flatten";` we can remove it

2019-12-08 14:56 UTC, bytewiz requested changes

2019-12-08 14:56 UTC, bytewiz commented on src/client/components/DropDown/DropDown.Component.jsx
> +        <List  onClick={onClickHandler} title={'...'}/>
No, I mean `onClickHandler ` should be `props. onClickHandler ` for this to work properly

2019-12-08 14:56 UTC, bytewiz commented on src/client/components/DropDown/DropDown.Component.jsx
> +const Anchor = props => {
Alright then feel free to delete from there if it is not needed or used

2019-12-08 14:56 UTC, bytewiz commented on src/client/components/DotButton/DotButton.story.js
> +  .add("with text", () => <DotButton title="..."></DotButton>);
I don't see it being added in the component

2019-12-08 14:56 UTC, bytewiz commented on src/client/components/DotButton/DotButton.story.js
> +  .add("with text", () => <DotButton title="..."></DotButton>);
there is no `prop` for `title` in the component [LINK](https://github.com/HackYourFuture-CPH/FP-annotatetheweb-class10/pull/45/files/5a2312e72be1a614b1179e9353a73fc3b8ff8ec3#diff-8f139db4a16fe2db89342d8475263fc8)

2019-12-08 15:08 UTC, bytewiz requested changes

2019-12-08 15:08 UTC, bytewiz commented on src/client/components/Input/Input.Component.jsx
> +const Input = props => {
This is still an uncontrolled component

2019-12-08 15:08 UTC, bytewiz commented on src/client/components/Input/Input.Component.jsx
> +        <div className="inputBox">
Can we be consistent using `inputBox ` => `input-box`

2019-12-09 20:57 UTC, berheg commented on src/client/components/Input/Input.Component.jsx
> +const Input = props => {
i have done it, it works.

2019-12-10 11:49 UTC, laila1222 requested changes
- Change Dropdown.Component.js to Dropdown.component.js , otherwise there is an error. Because you are importing '  import DropDown from "./DropDown.component"; ' in Dropdown.story.js.

- Change Input.Component to Input.component 

- Test are running 👍 

- I wrote you a comment in one of the files

2019-12-10 11:49 UTC, Laila1222 commented on src/client/components/DotButton/DotButton.story.js
> +import DotButton from "./DotButton.Component";
Change this to "./DotButton.component" since your component's name has been changed.

2019-12-10 12:03 UTC, berheg commented on src/client/components/DotButton/DotButton.story.js
> +import DotButton from "./DotButton.Component";
changed

2019-12-10 13:33 UTC, zkwsk submitted a review, later dismissed

2019-12-10 13:33 UTC, zkwsk commented on src/client/components/Button/Button.component.jsx
> +    <button className={"btnComponent"} onClick={props.onClickHandle}
```suggestion
    <button className="btnComponent" onClick={props.onClickHandle} 
```

The css class is a static string, so there is no point in surrounding it with `{}`. I'm not a great fan of the name, though. Css classes should not be camelCased. So in this case it should be: `.btn-component`. But then, I don't like that name either 🙈 Reason being that I don't like abbreviating "button" and the "component" part is kind of obvious as everything is a component. So my suggestion is to simply give it the class `.button`. If you want to make variations we could have a helper class such as `.small` that would make the button small if you add both the class `.button` and `.small` and so on.

We could also consider using something like BEM principles. In that case it would be `.button` for a regular button without any modifiers and `.button .button-small` for a small button, but I think this is a bit too advanced to introduce in this project.

That was a lot of discussion about naming a css class 😂

2019-12-10 13:33 UTC, zkwsk commented on src/client/components/Button/Button.component.jsx
> +        onBlur={props.onClickHandle}>{props.title}</button>
Why are you calling your click handler on blur? That would mean using TAB to go through the page would trigger clicking the button when you go past it.

2019-12-10 13:33 UTC, zkwsk commented on src/client/components/Button/Button.storybook.js
> +import Button from "./Button.Component";
```suggestion
import Button from "./Button.component";
```

2019-12-10 13:33 UTC, zkwsk commented on src/client/components/Container/CommentBlogCard/CommentBlogCard.Component.jsx
> +import List from "../../List/List.Component"
```suggestion
import List from "../../List/List.component"
```

2019-12-10 13:33 UTC, zkwsk commented on src/client/components/Container/CommentBox/blogCard.Component.jsx
> +import CommentList from "../CommentList/CommentList.Component";
Rename all of these to `.component`.

Please do the same for the rest of the files and make sure all files are actually named `.component` in lower-case.

2019-12-11 13:40 UTC, berheg commented on src/client/components/Button/Button.component.jsx
> +        onBlur={props.onClickHandle}>{props.title}</button>
ya, Zaki for the moment I am hidding in both conditions so I will use onBlur to put display property none .

2019-12-11 14:11 UTC, laila1222 approved these changes

2019-12-12 16:44 UTC, berheg commented on src/client/components/Button/Button.component.jsx
> +    <button className={"btnComponent"} onClick={props.onClickHandle}
I have done according to recommended

2019-12-12 16:46 UTC, berheg commented on src/client/components/DropDown/DropDown.Component.jsx
> +function onClickHandler() {
done

2019-12-12 16:47 UTC, berheg commented on src/client/stories/index.js
>  storiesOf("Button", module)
done

2019-12-12 16:47 UTC, berheg commented on src/client/stories/index.js
>  import { Button } from "@storybook/react/demo";
done

2019-12-12 16:47 UTC, berheg commented on src/client/stories/index.js
> +import { from } from "array-flatten";
done

2019-12-12 16:48 UTC, berheg commented on src/client/components/Container/CommentBox/blogCard.Component.jsx
> +import CommentList from "../CommentList/CommentList.Component";
changed

2019-12-12 17:01 UTC, berheg reviewed
all

2019-12-12 17:06 UTC, berheg commented on src/client/components/Input/Input.Component.jsx
> +        <div className="inputBox">
changed

2019-12-14 10:41 UTC, bytewiz requested changes

2019-12-14 10:41 UTC, bytewiz commented on src/client/container/CommentBox/BlogCard.component.jsx
> +      const newId=this.state.inputValue.length+1;
The component should not be responsible for creating `ids` for anything it should be a "dumb" as possible

2019-12-14 10:41 UTC, bytewiz commented on src/client/container/CommentBox/BlogCard.component.jsx
> +        {this.state.isEnter && this.state.inputValue && <CommentList inputValue ={this.state.inputValue}
`this.state.inputValue` this will always be `true` so no need, because
```
if ([]) { 
  // will always be true
}
```

2019-12-14 10:41 UTC, bytewiz commented on src/client/container/CommentBox/BlogCard.component.jsx
> +        {this.state.isEnter && this.state.inputValue && <CommentList inputValue ={this.state.inputValue}
What is `isEnter` even supposed to do?

2019-12-14 10:41 UTC, bytewiz commented on src/client/container/DropDown/DropDown.component.jsx
> +  const id = props.titleArray;
this doesn't seem to be used, remove it!

2019-12-14 10:41 UTC, bytewiz commented on src/client/container/DropDown/DropDown.component.jsx
> +      { props.titleArray.map(element => <Button title={element.title} onClickHandle={props.onClickHandle}/> )}
why do we have an array of elements if the `onClickHandle` is the same for all the elements?

2019-12-14 10:41 UTC, bytewiz commented on src/client/container/CommentBox/BlogCard.component.jsx
> +      const newId=this.state.inputValue.length+1;
the ids should come from outside

2019-12-14 12:00 UTC, berheg commented on src/client/container/DropDown/DropDown.component.jsx
> +      { props.titleArray.map(element => <Button title={element.title} onClickHandle={props.onClickHandle}/> )}
I use the same onClickHandle function but inside condition will be different based of clicked element

2019-12-14 12:08 UTC, berheg commented on src/client/container/CommentBox/BlogCard.component.jsx
> +      const newId=this.state.inputValue.length+1;
I agree but the function and states should move to App.js after merging and the component will be dump.

2019-12-14 12:09 UTC, berheg commented on src/client/container/CommentBox/BlogCard.component.jsx
> +        {this.state.isEnter && this.state.inputValue && <CommentList inputValue ={this.state.inputValue}
changed

2019-12-14 12:11 UTC, berheg commented on src/client/container/CommentBox/BlogCard.component.jsx
> +        {this.state.isEnter && this.state.inputValue && <CommentList inputValue ={this.state.inputValue}
There was an error while I was accessing the CommentList component. Now it is ok, I have removed it.

2019-12-14 12:11 UTC, berheg commented on src/client/container/DropDown/DropDown.component.jsx
> +  const id = props.titleArray;
I have removed it

2019-12-18 12:07 UTC, bytewiz requested changes

2019-12-18 12:07 UTC, bytewiz commented on src/client/container/CommentBox/BlogCard.component.jsx
> +      const newId=this.state.inputValue.length+1;
@berheg It should be removed now and you should pass in a function that returns the value and then pass in all the comments as a prop which you want to render

2019-12-18 15:05 UTC, berheg commented on src/client/container/CommentBox/BlogCard.component.jsx
> +      const newId=this.state.inputValue.length+1;
I have added a function to generate Id whenever it is called

2019-12-22 08:48 UTC, bytewiz requested changes

2019-12-22 08:48 UTC, bytewiz commented on src/client/container/CommentBox/BlogCard.component.jsx
> +      const newId= this.getIdForComment();
still not how it should be, you should not create an id for this the database will do that

2019-12-22 09:42 UTC, berheg commented on src/client/container/CommentBox/BlogCard.component.jsx
> +      const newId= this.getIdForComment();
I have removed it!

2019-12-22 12:15 UTC, bytewiz approved these changes

2019-12-22 12:17 UTC, merged