added the navbar component
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #49
Opened 2019-11-28 22:58 UTC by Fatemeh-Pakpour

2019-11-29 10:39 UTC, bytewiz requested changes
Looks good only a few minor comments 👍

2019-11-29 10:39 UTC, bytewiz commented on src/client/components/NavBar/NavBar.component.js
> +      <a href="#">
Maybe there is should a prop for the `href` as well so you can pass in a link? and then the default can be `"#"`? :)

2019-11-29 10:39 UTC, bytewiz commented on src/client/components/NavBar/NavBar.css
> +@import url("https://fonts.googleapis.com/css?family=Open+Sans|Pacifico&display=swap");
This should go in a general `css` file and not for a specific component 👍 so we can remove it from here

2019-11-29 10:39 UTC, bytewiz commented on src/client/components/NavBar/NavBar.css
> +a:link {
be aware of using the `global` selectors unless you have 100% sure all `<a>` should look the exact same and if so this should probably go in a generic `css` file that is loaded for the entire app and not only for the component

2019-11-29 10:39 UTC, bytewiz commented on src/client/components/NavBar/NavBar.story.js
> +      { title: "Annotate", id: 1 },
if we added prop for links then we can add here as well 👍

2019-11-29 10:39 UTC, bytewiz commented on src/client/stories/index.js
>  storiesOf("Button", module)
Can we delete this one? 👍 it is no longer used

2019-11-29 10:39 UTC, bytewiz commented on src/client/stories/index.js
>  import { Button } from "@storybook/react/demo";
Can we delete this one? 👍 it is no longer used

2019-12-01 13:00 UTC, bytewiz requested changes

2019-12-01 13:00 UTC, bytewiz commented on src/client/components/NavBar/NavBar.story.js
> +    href ="#"
I think I would add the `href`prop for each of the elements so they can each have a different link

2019-12-01 13:00 UTC, bytewiz commented on src/client/components/NavBar/NavBar.story.js
> +    href ="#"
@Fatemeh-Pakpour ☝️

2019-12-03 19:45 UTC, Laila1222 commented on src/client/components/RegisterButton/RegisterButton.css
> +    letter-spacing: 1px;
Maybe add cursor: pointer here? 
So it also looks like it's a button when we hover over it.

2019-12-03 19:56 UTC, laila1222 reviewed
I just had one suggestion in the register button css file. 👍 
The tests didn't run for me ('No tests found related to files changed since last commit.'), but it might have been something to do with me, as earlier today it worked.

2019-12-03 21:20 UTC, Laila1222 commented
> I just had one suggestion in the register button css file. 👍
> The tests didn't run for me ('No tests found related to files changed since last commit.'), but it might have been something to do with me, as earlier today it worked.

This test problem I described shows error only on my computer locally, as it worked for Olha. So nothing to do for you related to it ;)

2019-12-04 08:06 UTC, OlkaA commented on src/client/components/RegisterButton/RegisterButton.css
> +    letter-spacing: 1px;
Great job, so much work done.
My only suggestion is to add styling for mobile version, so items could be shown in column.

2019-12-10 11:53 UTC, OlkaA requested changes

2019-12-10 11:53 UTC, OlkaA commented on src/client/components/NavBar/NavBar.component.js
> +      </a>
It renders, but isn't "a" should be inside "li" element?
Like this:
ul -> li -> a -> Text -< /a -< /li -< /ul

2019-12-10 11:53 UTC, OlkaA commented on src/client/components/NavBar/NavBar.test.js
> +    expect(container.children.length).toBe(1);
I am not quite sure how this test is working.
I have a suggestion, maybe it is better to do it something like this:
expect(container.getElementsByTagName('a')[0].innerHTML).toBe('Annotate');

2019-12-14 15:57 UTC, Fatemeh-Pakpour commented on src/client/components/NavBar/NavBar.test.js
> +    expect(container.children.length).toBe(1);
Thank you for your feedback, I used your suggestion and that worded.

2019-12-15 11:59 UTC, OlkaA approved these changes

2019-12-15 12:57 UTC, Fatemeh-Pakpour commented on src/client/components/NavBar/NavBar.component.js
> +      <a href="#">
I fixed that.

2019-12-15 12:58 UTC, Fatemeh-Pakpour commented on src/client/components/NavBar/NavBar.story.js
> +    href ="#"
I fixed that.

2019-12-15 12:59 UTC, Fatemeh-Pakpour commented on src/client/components/RegisterButton/RegisterButton.css
> +    letter-spacing: 1px;
I added cursor:pointer  to the register button and the nav links.

2019-12-15 13:00 UTC, Fatemeh-Pakpour commented on src/client/components/NavBar/NavBar.component.js
> +      </a>
I

2019-12-16 21:49 UTC, Fatemeh-Pakpour commented
@bytewiz could you please approve my pull request?

2019-12-17 10:35 UTC, bytewiz approved these changes

2019-12-17 10:49 UTC, merged