Issue #29 Add profile summery
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #50
Opened 2019-11-30 01:01 UTC by azinkamran

add profile summery photo and name
#29

2019-12-01 11:26 UTC, hleote approved these changes
Nice work 🙂 💯 👍 
Nice use of functional components.
Overall everything good, left a few comments related to small things you might want to think about changing.

2019-12-01 11:26 UTC, hleote commented on src/client/components/ProfileSummery/ProfileSummery.story.js
> +));
Do you need to have the wrapping `div` here? It doesn't seem so.
I think you can just have -> `storiesOf("ProfileSummery", module).add("ProfileSummery", () => <ProfileSummery profileName="Kseiina Zar" profileImage={profile} />);`

2019-12-01 11:26 UTC, hleote commented on src/client/components/ProfileSummery/ProfileSummery.story.js
> +
Just a small typo here.
It should be `ProfileSummary` instead of `ProfileSummery` 🙂

2019-12-01 11:26 UTC, hleote commented on src/client/components/ProfileSummery/ProfileSummery.component.js
> +export default ProfileSummery;
Nice & clean functional component.
Good work 👍 💯

2019-12-04 20:36 UTC, JustinaOyov commented on src/client/components/ProfileSummery/ProfileSummery.story.js
> +));
Really nice component, good job!! PR almost ready for approval if you incorporate @hleote suggestions above.

2019-12-05 02:00 UTC, azinkamran commented on src/client/components/ProfileSummery/ProfileSummery.story.js
> +
I changed all the files for that typo

2019-12-08 11:33 UTC, bytewiz requested changes
Looks good I just have some grumpy old man comments 👴 😄

2019-12-08 11:33 UTC, bytewiz commented on src/client/components/ProfileSummary/ProfileSummary.css
> +.profile-Image {
Just a small thing but can we keep lowercase for css classes? :) I think that would be great for consistency :v:

so e.g. `.profile-Image` => `.profile-image`

2019-12-08 11:33 UTC, bytewiz commented on src/client/components/ProfileSummary/ProfileSummary.css
> +.profile-Name {
Just a small thing but can we keep lowercase for css classes? :) I think that would be great for consistency :v:

so e.g. `.profile-Name ` => `.profile-name`

2019-12-10 18:50 UTC, azinkamran commented on src/client/components/ProfileSummary/ProfileSummary.css
> +.profile-Image {
done

2019-12-10 18:51 UTC, azinkamran commented on src/client/components/ProfileSummary/ProfileSummary.css
> +.profile-Name {
done

2019-12-14 10:43 UTC, bytewiz approved these changes

2019-12-14 10:46 UTC, merged