issue#18 Login Form
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #51
Opened 2019-11-30 18:06 UTC by rakhshanda-rashid

All required changes done...

#18

2019-12-01 17:50 UTC, hleote requested changes
You have built many nice things!! Nice!! 👍 💯 🙂 

I've added a few comments that I think might help you improve things. Please check them out.
If you have any questions don't hesitate to ask. 🙂

2019-12-01 17:50 UTC, hleote commented on src/client/components/Button/Button.component.js
> +export default FormButtons;
I can see you're importing some libraries that you don't seem to be using.

You can probably remove these imports `import { library } from '@fortawesome/fontawesome-svg-core';`, `import { fab } from '@fortawesome/free-brands-svg-icons';` and also when you have functional components you don't need to import `Component` since you're not using it.

Just import React like this:
`import React from 'react';`

2019-12-01 17:50 UTC, hleote commented on src/client/components/Button/Button.story.js
> +
Please remove all this spacing.

2019-12-01 17:50 UTC, hleote commented on src/client/components/FormField/FormField.component.js
> +import React,{Component} from 'react';
You can remove the `Component` from the import.

2019-12-01 17:50 UTC, hleote commented on src/client/components/FormField/FormField.component.js
> +import { useState } from "react";
You can remove this import from here you don't need it.
This is a stateless component so you don't need to do any state manipulations.

2019-12-01 17:50 UTC, hleote commented on src/client/components/FormField/FormField.component.js
> +)
You seem to have some indentation/spacing issues here...
Make sure you have a space after each prop in the arguments of your component declaration. 

Something like this:
`const FormField = ({ text, box, title, inputType, textHolder, inputClass, changeHandler }) => {}`

It's normally better in terms of readability to have your props declared with camelcase, as you can see above. 
You can remove the first and last `(` `)` in this file. You don't need them.

2019-12-01 17:50 UTC, hleote commented on src/client/components/FormLine/FormLine.component.js
> +)
Some more issues with indentation and spacing.
Here you can just declare your component like this:

```
const FormLine = () => {
  return (
    <div className='form-line'>Or</div>
  );
}
``` 

Or even nicer like this:

```
const FormLine = () => <div className='form-line'>Or</div>
```

2019-12-01 17:50 UTC, hleote commented on src/client/components/FormTitle/FormTitle.component.js
> +import React,{Component} from 'react';
You can remove the `Component` from the import

2019-12-01 17:50 UTC, hleote commented on src/client/components/FormTitle/FormTitle.component.js
> +  })
You can have similar as the `FormLine` component.

``` 
const FormTitle = () => <div className='form-title'>Login to Annotate the web</div>
```

You can also create a more generic component called `Text` for example to which you will pass all texts you want to show and a `className` prop for example, and then reuse that component when you have to show text.

2019-12-01 18:00 UTC, rakhshanda-rashid commented on src/client/components/Button/Button.component.js
> +export default FormButtons;
changes done

2019-12-01 18:01 UTC, rakhshanda-rashid commented on src/client/components/Button/Button.story.js
> +
done

2019-12-01 18:05 UTC, rakhshanda-rashid commented on src/client/components/FormField/FormField.component.js
> +import { useState } from "react";
done

2019-12-01 18:08 UTC, rakhshanda-rashid commented on src/client/components/FormField/FormField.component.js
> +)
done

2019-12-01 18:09 UTC, rakhshanda-rashid commented on src/client/components/FormTitle/FormTitle.component.js
> +import React,{Component} from 'react';
### done

2019-12-01 18:12 UTC, rakhshanda-rashid commented on src/client/components/FormLine/FormLine.component.js
> +)
done

2019-12-01 18:13 UTC, rakhshanda-rashid commented on src/client/components/FormTitle/FormTitle.component.js
> +  })
done

2019-12-04 23:37 UTC, JonathanMH commented on package.json
> -    "storybook": "cd ./src/client/ && start-storybook -p 3007"
These should stay in the file to make sure the different scripts can be run, not only `test`. You can add an additional entry called "test":"jest" though

2019-12-05 00:34 UTC, JustinaOyov commented on src/client/components/FormField/FormField.component.js
> +const FormField = ( {text, box, title, inputtype, textholder, inputclass, changehandler} ) => {
Nice work! Please note that it is a good practice to declare your props/variables using camelcase naming convention as shown below:
const FormField = ({ text, box, title, inputType, textHolder, inputClass, changeHandler }) => {}

2019-12-05 00:34 UTC, JustinaOyov commented on src/client/components/FormLine/FormLine.component.js
>  import React,{Component} from 'react';
{Component} is not used, you can remove from the import.

2019-12-05 00:34 UTC, JustinaOyov commented on package.json
> -    "build": "webpack --mode production",
Unable to run storybook, the run script has been deleted from package.json. I am not sure if lines 10-16 was deleted in error but please review and re-instate script where necessary.

2019-12-05 00:34 UTC, JustinaOyov commented on src/client/components/FormField/FormField.story.js
> +                                   inputtype='email'
Declare all props/variable with camelcase e,g. change inputtype to inputType

2019-12-05 00:34 UTC, JustinaOyov commented on src/client/components/FormField/FormField.test.js
> +       let inputtype;
Declare all props/variable with camelcase e,g. inputtype change to inputType. 
Check your code and ensure camelcase naming convention is adopted throughout.

2019-12-05 00:34 UTC, JustinaOyov commented on src/client/components/Button/Button.test.js
> +  });
This file is outdated. I have reviewed the updated version which is accessible by clicking the "Files changed" tab above.

2019-12-07 11:25 UTC, hleote reviewed
@rakhshanda-rashid I've fixed an issue with your package.json.
Your project builds and runs fine and the components you created seem fine. 👍

2019-12-07 12:02 UTC, hleote commented on src/client/components/Button/Button.component.js
> +export default FormButtons;
Something for you to think about the naming here:
`FormButtons` it's a bit too generic. Don't you think? One form can have different types of buttons - submit button, cancel button...

You can, of course, have one generic button that you will reuse in your form. 
In that case I would call it `FormButton`.
Another good practice is to make sure your components have the same name as your file. To avoid any issues when importing files and also for better readability.
One thing to keep in mind is that when you use `export default` inside a component that component is exported with the file name, so sometimes this can be confusing.
A good way to not have these problems is just to use the same naming for file and the component being default exported in that file.

2019-12-07 12:05 UTC, hleote commented on src/client/components/FormField/FormField.test.js
> +  );
You have some indentation issues here.
Using camel case would also help.
So you should have something like this instead.

```
if(inputType === 'email' || inputType === 'password') {
  const {  getByText } = render(<FormButtons onChange={handleChange} />);
  fireEvent.click(getByText(inputtype));
  expect(handleChange).toHaveTextContent("1");
}```

2019-12-07 12:06 UTC, hleote commented on src/client/components/FormLine/FormLine.test.js
> +
Here you're passing a mocked function.
You  don't need to do this in this case.
If you just wanna check the the `Or` text is there what you're doing on lines 9 and 10 is enough. You don't need to add the mocked function to the className.

2019-12-07 12:09 UTC, hleote approved these changes
Added a few more comments.
I would say that after you apply those changes this seems ready to be merged 👍 💯

2019-12-08 11:44 UTC, bytewiz commented
@rakhshanda-rashid Do you have the environment variables setup for the project? it seems that the Travis is failing on you branch

2019-12-08 11:45 UTC, bytewiz commented
Also the `branch` name should be more descriptive e.g. `feature/18/login-form`

2019-12-08 13:29 UTC, zkwsk requested changes

2019-12-08 13:29 UTC, zkwsk commented on package.json
> +>>>>>>> da5ad3bdae26d6b96dc11cabef36eefb31dfa41c
You need to fix this merge conflict and those above to be able to run `npm install`. That's why travis is failing.

2019-12-08 19:04 UTC, rakhshanda-rashid commented on src/client/components/FormLine/FormLine.test.js
> +
you mean i need to remove line 8

2019-12-08 19:13 UTC, rakhshanda-rashid commented on src/client/components/FormLine/FormLine.test.js
> +
u mean i need to remove line 8

2019-12-11 20:03 UTC, closed without merging