Feature/17/signup form
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #52
Opened 2019-11-30 19:20 UTC by mo3ni

# 17 
Sign up form

2019-12-01 13:47 UTC, hleote requested changes
You've created a lot of good stuff 👍 🙂 
You probably need to change the naming/file names of your components to be more compliant with React components naming standards.
Having file names with snakecase is normally not how it's done.
So you should probably have something like `SignupTitle.js` instead of `signup_title.js`.

I left a few more comments. 🙂

2019-12-01 13:47 UTC, hleote commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +// import { fagoogle } from '@fortawesome/free-solid-svg-icons'
Remove this duplicated commented out line.

2019-12-01 13:47 UTC, hleote commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +import '@fortawesome/free-brands-svg-icons';
If we are supposed to use this new dependency in our project you will need import it like this:
for example -> `import { faFacebookF } from '@fortawesome/free-brands-svg-icons'` 
Depending on the icons you want to use.

2019-12-01 13:47 UTC, hleote commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +    }
You should probably give a more meaningful name to this `googlebtn` function, a name more according to naming standards for this cases.
This is an on click listener so you should probably call it something like `onClick` or `onClickHandler` or if this is the signup button you could call it something like `onClickSignup` for example.

You should remove the `console.log` since as mentioned in the readme file you shouldn't commit those.

<img width="854" alt="Screenshot 2019-12-01 at 13 18 05" src="https://user-images.githubusercontent.com/5212392/69913793-11a7ed80-143d-11ea-99e3-a36506710daf.png">

2019-12-01 13:47 UTC, hleote commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +const SignupButtons =({title,signupBtn,text,logo,signupBtnTxt})=>{
You should probably add some proper spacing between all your elements/props when you declare a variable.
In this case something like this is cleaner and more readable ->
`const SignupButtons =({ title, signupBtn, text, logo, signupBtnTxt }) => {}`

2019-12-01 13:47 UTC, hleote commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +                </button>
The indentation here is quite relevant.
Indentation is very import for better code readability.
So in this case something like this:

```
<button onclick={googlebtn} className={signupBtn}>
  <FontAwesomeIcon icon={logo} className={text}/>
  <h3 className={signupBtnTxt} icon={logo}>
    {title}
  </h3>
</button>
```

2019-12-01 13:47 UTC, hleote commented on src/client/components/signup/checkbox/signup_checkbox.js
> +}
I guess we will have some props being passed to this component at some point. Right?
The Terms of services url or something like that.
I like the indentation here 👍

2019-12-01 13:47 UTC, hleote commented on src/client/components/signup/signup.css
> +}
Please fix the indentation here.
The css rules should be indented inside their class.

Like you have here:

<img width="398" alt="Screenshot 2019-12-01 at 13 36 17" src="https://user-images.githubusercontent.com/5212392/69914022-998ef700-143f-11ea-9ddd-66b1ea357ca9.png">

2019-12-01 13:47 UTC, hleote commented on src/client/components/signup/signupFormLine/signup_form_line.js
> +}
More indentation/spacing issues

2019-12-01 13:47 UTC, hleote commented on src/client/components/signup/signupTextFields/signup_password.js
> +})
You probably should change this declaration.
You've declare it as a function inside a function...
If you notice the component declaration has an extra pair of `( )`.

Having like this should be the way -> `const SignupPassword = ()=>{}`

instead of `const SignupPassword = (()=>{})`

2019-12-01 13:47 UTC, hleote commented on src/client/components/signup/title/signup_title.js
> +})
You should probably create one single input that you can then reuse in the username and password for example.
You can just pass a different prop called `type` which then you will use in your component to render elements of type `password` or type `text`.

2019-12-02 15:39 UTC, mo3ni commented on src/client/components/signup/checkbox/signup_checkbox.js
> +}
yes;

2019-12-02 15:42 UTC, mo3ni commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +// import { fagoogle } from '@fortawesome/free-solid-svg-icons'
done

2019-12-02 15:44 UTC, mo3ni commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +import '@fortawesome/free-brands-svg-icons';
Here I didn't import google logo I just used font awesome and than I did it on index + css styling; 
also removed import { FontAwesomeIcon } from '@fortawesome/react-fontawesome' & import '@fortawesome/free-brands-svg-icons'; so in that case fontawesome don't work

2019-12-02 15:45 UTC, mo3ni commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +import '@fortawesome/free-brands-svg-icons';
So I used this two and than called {fagoogle, fafacebook, fatwitter} on index file

2019-12-02 15:45 UTC, mo3ni commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +    }
fixed

2019-12-02 15:45 UTC, mo3ni commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +const SignupButtons =({title,signupBtn,text,logo,signupBtnTxt})=>{
fixed

2019-12-02 15:45 UTC, mo3ni commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +                </button>
fixed

2019-12-02 15:46 UTC, mo3ni commented on src/client/components/signup/signup.css
> +}
fixed

2019-12-02 15:46 UTC, mo3ni commented on src/client/components/signup/signupFormLine/signup_form_line.js
> +}
done

2019-12-02 15:46 UTC, mo3ni commented on src/client/components/signup/signupTextFields/signup_password.js
> +})
done

2019-12-03 08:11 UTC, hleote commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +import '@fortawesome/free-brands-svg-icons';
What happens when you remove this? 👇 
`import '@fortawesome/free-brands-svg-icons';`

It doesn't seem that you need it...

2019-12-03 08:18 UTC, hleote requested changes
Cool that you made some of the changes. I think that's an improvement 🙂 
I think you probably still need to change a couple of things.
I've noticed that the components in storybook are strangely positioned....
You probably need to address that.
You need, for example, to change the css rules for this class:
`signup-email-box` 

It probably also makes sense to implement all the logic related, to the `SignupButtons` for example.
Instead of having an empty `onClickHandler`. 👇 

![Screenshot 2019-12-03 at 09 17 11](https://user-images.githubusercontent.com/5212392/70032482-db3db000-15ad-11ea-9f37-414360a64c32.png)

Take your time there is no rush in merging this 🙂

2019-12-04 21:28 UTC, mo3ni commented on src/client/components/signup/SignupButtons/Signup_buttons.js
> +import '@fortawesome/free-brands-svg-icons';
yeap; I just remove it 😄

2019-12-07 12:30 UTC, hleote approved these changes
Nice 👍 💯 
I've fixed your merge conflicts.
As a reminder keep in mind that when you install an npm module that you're going to use in your project you need to add it to your package.json as a dependency.

So when you install it you need to do `npm i <package name> --save` to save it in the dependencies object, or `npm i <package name> --save-dev` if you wanna save it to the devDependencies.

You can find out more here:
https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file

2019-12-08 11:57 UTC, bytewiz requested changes
Looks good, have a few comments

Mainly important are the ones where the components are uncontrolled and maybe should not be 👍

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/SignupButtons/SignupButtons.js
> +  function onClickHandler() {
I don't think we should have this function here.

I would rather consider passing in a `prop` for when you click the button so you can control it from outside of this component as this should not contain any logic :)

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/checkbox/signupCheckBox.js
> +const CheckBox = ({}) => {
I think this component should maybe take a `prop` or some sort `state` otherwise we have an uncontrolled component and it will / can be hard to get the actual value of the `Checkbox`.

I believe both `value` and `onChange` should be passed as `props` here

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupTitle {
Generally, for `css` classes lets use `kebab-case` so for example `signupTitle` becomes `signup-title`, nothing wrong with this but will just make more consistent as most others use this format and we then have it consistent throughout

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.googleSignupButton {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupBtnTxt {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.CreateAccountBtn {
same as above for the class name (and all lowercase)

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupCreateAccountTxt {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.googleLogoAlign {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.twitterBtn.facebookBtn {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupFormLine {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupFormLine:before,
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupFormLine:before {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupFormLine:after {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupEmail {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupCheckBoxTxt {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupEmailBox {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupUserNameTxt.signupFullNameTxt {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupFullNameBox.signupUserNameBox {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupPassword {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signup.css
> +.signupPasswordBox {
same as above for the class name

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signupTextFields/signupEmailAddressTxtField.js
> +const SignupEmailAddress = () => {
I don't think this should be an uncontrolled component

2019-12-08 11:57 UTC, bytewiz commented on src/client/components/signup/signupTextFields/signupPassword.js
> +const SignupPassword = () => {
I don't think this should be an uncontrolled component

2019-12-08 11:57 UTC, bytewiz commented on src/client/stories/index.js
> +storiesOf("components", module)
Could we maybe rename this to `Form components` atleast? just `components` is too generic

2019-12-14 10:54 UTC, bytewiz submitted a review, later dismissed

2019-12-14 10:54 UTC, bytewiz commented on src/client/components/signup/SignupButtons/signupButton.test.js
> +  if (title === "Create Account" || title === "signup with Google") {
This breaks the test, it will never be true and the test will not work as expected, remove the condition (what was the reason for adding it in the first place)? (as title is undefined)

2019-12-14 10:54 UTC, bytewiz commented on src/client/components/signup/checkbox/signupCheckBox.js
> +  text1,
Probably not the best names also as `text1` and `text2` for example are two completely different things, same goes for `text3` and `text4`

2019-12-14 10:54 UTC, bytewiz commented on src/client/components/signup/signupTextFields/signupTextFields.test.js
> +  if (
Same here, the `title` is not defined so this will not work as expected

2019-12-15 15:11 UTC, mo3ni commented on src/client/components/signup/SignupButtons/signupButton.test.js
> +  if (title === "Create Account" || title === "signup with Google") {
fixed

2019-12-15 15:18 UTC, mo3ni commented on src/client/components/signup/checkbox/signupCheckBox.js
> +  text1,
changed

2019-12-18 14:51 UTC, zkwsk requested changes

2019-12-18 14:51 UTC, zkwsk commented on src/client/stories/index.js
> +storiesOf("components", module)
Yeah, please call this one "Form components"

2019-12-18 15:12 UTC, rakhshanda-rashid approved these changes

2019-12-18 16:15 UTC, zkwsk commented
I got a look at the components in Storybook now.

There is a problem with most of the components. They are not "portable". You cannot take them out and use them somewhere else in the application because you have added styling that belongs on parent components. Mostly layout stuff. 

So when I go to storybook and look at for example the email field component, you've set this:
```
position: absolute;
left: 1139px;
```

First of all, by using position absolute and pixel values, you are breaking any kind of responsive behavior.

Second, layout (i.e. the positioning of the component on the page) should never be the responsibility of the individual component. We will make the layout in components that are putting together multiple components - i.e. parent components to what you are doing now.

If we load two email fields on the same page, the way it is done now, they would sit right on top of each other.

I'm running out the door at the moment, but generally you need to go back in your components and strip out all position absolute related stuff.

Also, I noticed that you are not following naming conventions for components. Tests and stories are fine, but components should be: `MyComponent.component.js`.

2019-12-18 23:35 UTC, zkwsk approved these changes

2019-12-19 05:40 UTC, merged