Issue #30 - Fix css naming and write test for Content component.
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #53
Opened 2019-12-02 18:17 UTC by aina21

- add test for content component 
- fix naming issue

#30

2019-12-03 11:58 UTC, zkwsk requested changes
Looks good, but I'm not a great fan of your testing approach. See comment :)

2019-12-03 11:58 UTC, zkwsk commented on src/client/components/content/Context.test.js
> +    .substring(20);
Interesting idea to generate random strings as input data. But we generally want our tests to look the same on every run. What if on one run your random text generator hits a "magic" text string that breaks something. You try to run the test again and it passes. You end up chasing ghosts. I don't think it would happen here, but if you really want something like this, generate a number of random inputs in advance and set up your test to run against all of them. Every time.

But if you think there is a risk that certain strings will break things it's probably better to write tests that are deliberately designed to test the system.

- What happens if you pass a very long string?
- What happens if you pass an empty string? `""`
- What happens if you pass a string that is actually a number? `23`
- What happens if you pass a string that contains javascript code? `eval('2 + 2')`

2019-12-04 10:34 UTC, OlkaA commented on src/client/stories/index.js
> +import { Content } from "../components/Content/Content.story";
I would suggest to name a folder for a component - Content, starting with UpperCase letter, otherwise it shows error, when trying to connect to stories/index.

"ERROR in ./stories/index.js
Module not found: Error: [CaseSensitivePathsPlugin] `C:\Olka\repos\HYF - final project\src\client\components\Content\Content.story.js` does not match the corresponding path on disk `content`."

2019-12-08 09:16 UTC, aina21 commented on src/client/components/content/Context.test.js
> +    .substring(20);
Thanks, I did fix it :)

2019-12-08 09:16 UTC, aina21 commented on src/client/stories/index.js
> +import { Content } from "../components/Content/Content.story";
Thanks, I did fix it :)

2019-12-08 12:00 UTC, bytewiz approved these changes
Looks good 👍

2019-12-10 12:28 UTC, laila1222 approved these changes
You have a conflict that needs to be resolved in the stories/index.js file. 
Otherwise looks good! 👍

2019-12-10 12:28 UTC, laila1222 commented on src/client/components/content/Context.test.js
> +import React from "react";
Maybe there is a typo in the file name: context  instead of content? 
If it was on purpose, then ignore this comment :)

2019-12-11 21:01 UTC, aina21 commented on src/client/components/content/Context.test.js
> +import React from "react";
I did fix it in my last commit

2019-12-14 10:57 UTC, merged