#14 Header component, css and storybook added
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #55
Opened 2019-12-04 17:49 UTC by adh86

2019-12-07 11:30 UTC, laila1222 requested changes
Nice header. I requested some changes though, see them in the comment. 👍 
Also: 
In order to have your components visible in story book, you need to impor its .story file in the src/client/stories/index.js file

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +  position: absolute;
I would remove this with the top and left properties also as we want the header to be on top of the page.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +  width: 1767px;
Consider using rem instead of pixels here and other places too, in order to make it responsive.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +  position: absolute;
I would remove this line, and the left and top properties too, for the same reason as I wrote in .header.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +.navigation {
I don't see if this classname was used in your header.component file, so if we don't need it here for the header part, you could remove this part.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +.RegisterBtn {
I don't see if this classname was used in your header.component file, so if we don't need it here for the header part, you could remove this part.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +.RegisterText {
I don't see if this classname was used in your header.component file, so if we don't need it here for the header part, you could remove this part.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +.Navigate {
I don't see if this classname was used in your header.component file, so if we don't need it here for the header part, you could remove this part.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +.Rectangle11 {
I don't see if this classname was used in your header.component file, so if we don't need it here for the header part, you could remove this part.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +.Anot {
I don't see if this classname was used in your header.component file, so if we don't need it here for the header part, you could remove this part.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +.line4 {
I don't see if this classname was used in your header.component file, so if we don't need it here for the header part, you could remove this part.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +.Abt {
I don't see if this classname was used in your header.component file, so if we don't need it here for the header part, you could remove this part.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.css
> +.lgn {
I don't see if this classname was used in your header.component file, so if we don't need it here for the header part, you could remove this part.

2019-12-07 11:30 UTC, Laila1222 commented on src/client/components/Header/Header.Component.jsx
> +import { Link } from "@reach/router";
this line/import is not used, you can remove it.

2019-12-08 13:55 UTC, adh86 commented on src/client/components/Header/Header.Component.jsx
> +import { Link } from "@reach/router";
done

2019-12-08 14:07 UTC, adh86 commented on src/client/components/Header/Header.css
> +  position: absolute;
i get idea from figma

2019-12-08 14:07 UTC, adh86 commented on src/client/components/Header/Header.css
> +.navigation {
ok I done

2019-12-08 14:34 UTC, adh86 commented on src/client/components/Header/Header.css
> +  width: 1767px;
👍

2019-12-10 12:34 UTC, laila1222 approved these changes

2019-12-10 13:50 UTC, zkwsk approved these changes

2019-12-10 13:50 UTC, merged