Feature/36#endpoint read annotation
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #57
Opened 2019-12-06 19:41 UTC by mo3ni

#36 
Endpoint to read an annotation:

- [ ] annotation controller

- [ ] annotation router 

- [ ] test router

2019-12-08 14:34 UTC, JonathanMH commented on src/server/migrations/20191207165524_annotations.js
> +    table.timestamp("deleted_at").notNullable();
If we don't have a default value, we should allow `NULL` values

2019-12-08 14:36 UTC, JonathanMH commented on src/server/api/controllers/annotations.controller.js
> +const getAnnotations = async req => {
do we need to pass the `req` to this function? Otherwise let's replace it with `()` to make clear that we don't need it in the function

2019-12-08 19:55 UTC, rakhshanda-rashid requested changes

2019-12-08 19:55 UTC, rakhshanda-rashid commented on src/client/component/signup/SignupButtons/Signup_buttons.js
> +const SignupButtons =({title,signupBtn,text,logo,signupBtnTxt})=>{
I would say that naming convention for the component should be SignupButton instead of SignupButtons because it is reuseable component..and also it should matches with your file name so it would easy for others to view and understand

2019-12-08 19:55 UTC, rakhshanda-rashid commented on src/client/component/signup/signup.css
> +font-family: Open Sans;
try to follow kebab-case for class names instead of camelcase use signup-title instead of signupTitle

2019-12-14 11:00 UTC, bytewiz requested changes
Everything NOT related to endpoints and backend has to be removed from this branch before it will get approved, please revert those changes from this branch

2019-12-22 12:01 UTC, closed without merging