Feature/31/mobile menu
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #60
Opened 2019-12-08 01:04 UTC by azinkamran

2019-12-08 14:41 UTC, bytewiz requested changes
Looks good 👍 but can we change all the class names to use `kebab-case` and lowercased letters instead? :) 

Example this `MobileMenu-menuwrap` will be this `mobile-menu-menuwrap`

2019-12-08 15:07 UTC, Fatemeh-Pakpour requested changes

2019-12-08 15:07 UTC, Fatemeh-Pakpour commented on src/client/components/MobileMenu/MobileMenu.css
> +.MobileMenu-menuwrap {
Good job, I have a few comment. The mobile menu does not look good in some of the mobile versions like GalaxyS5, iphone 6/7/8. I sent the screen shot of them on the slack to see what I mean.

2019-12-08 15:07 UTC, Fatemeh-Pakpour commented on src/client/components/MobileMenu/MobileMenu.css
> +.MobileMenu-toggler:checked:hover + .MobileMenu-hamburgur > div {
The hamburger menu should place on the right of the page. Just follow the design on this link :
https://www.figma.com/file/QYeFmfAU7XAaewnskogsxH/Class10-Final-Project-Mockups?node-id=0%3A1

2019-12-13 04:18 UTC, azinkamran commented on src/client/components/MobileMenu/MobileMenu.css
> +.MobileMenu-menuwrap {
thanks for the feedback :), I resolved it

2019-12-13 04:18 UTC, azinkamran commented on src/client/components/MobileMenu/MobileMenu.css
> +.MobileMenu-toggler:checked:hover + .MobileMenu-hamburgur > div {
thanks for the feedback:)

2019-12-14 11:02 UTC, merged