Feauture/16/navigation component
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #65
Opened 2019-12-08 12:31 UTC by adh86

2019-12-08 14:10 UTC, JonathanMH requested changes

2019-12-08 14:10 UTC, JonathanMH commented on src/client/components/Navigation/Navigation.css
> +.navigation {
Instead of positioning every element / navigation link absolutely, we should use methods like floats or flexbox to position them. Here's an example that goes over a similar problem: https://medium.com/flexbox-and-grids/the-most-popular-navigation-bars-created-with-flexbox-6c0f59f55686

2019-12-08 14:10 UTC, JonathanMH commented on src/client/stories/index.js
> +import{Footer } from "../components/Footer/Footer.story";
As long as `Header` and `Footer` are in here, the storybook will not build for me locally, since the components can't be found.

2019-12-08 14:10 UTC, JonathanMH commented on src/client/components/Navigation/Navigation.Component.jsx
> +                    <div className='Anot'>Annotate</div>
The `div` elements that should link the user to a route, should be `Link` components from react-router, like already imported in the top. Reference to the documentation: https://reacttraining.com/react-router/web/api/Link

2019-12-08 14:50 UTC, bytewiz requested changes

2019-12-08 14:50 UTC, bytewiz commented on src/client/components/Navigation/Navigation.css
> +.navigation {
Also can we stick to `kebab-case` for `css` classes so it is consistent with the rest of the code styles 👍 

so for example class name `RegisterText ` would be `register-text `

2019-12-08 14:50 UTC, bytewiz commented on src/client/components/Navigation/Navigation.css
> +.Rectangle11 {
Avoid having "random" numbers in the class names

2019-12-08 14:50 UTC, bytewiz commented on src/client/components/Navigation/Navigation.css
> +.Abt {
it would be better with some more meaningful names

2019-12-08 14:50 UTC, bytewiz commented on src/client/components/Navigation/Navigation.story.js
> +  return <Navigation ></Navigation>;
You could just write it like `<Navigation />` if there is no children inside it

2019-12-08 15:03 UTC, aina21 requested changes

2019-12-08 15:03 UTC, aina21 commented on src/client/components/Navigation/Navigation.css
> +@import url("https://fonts.googleapis.com/css?family=Open+Sans|Pacifico&display=swap");
You should add font to global css to be share with other components as well. Actually it is updated in develop branch, you can remove from here and update your develop branch and use it :).

2019-12-08 15:03 UTC, aina21 commented on src/client/components/Navigation/Navigation.css
> +.RegisterBtn {
It is a suggestion to use a css class name with hyphen. for example : register-btn

2019-12-14 11:05 UTC, bytewiz requested changes
One really small comment else it looks good 👍

2019-12-14 11:05 UTC, bytewiz commented on src/client/components/Navigation/Navigation.css
> +a {
Be careful with global selectors, this will affect all `anchor` tags on the page, please rename this or add a pre-fix to this, it will save a lot of headaches later 👍

2019-12-15 13:51 UTC, closed without merging

2019-12-15 13:53 UTC, adh86 commented
I close this PR because it was same as Fatemeh task.