Feauture/15/footer component
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #66
Opened 2019-12-08 12:31 UTC by adh86

2019-12-08 20:04 UTC, rakhshanda-rashid requested changes

2019-12-08 20:04 UTC, rakhshanda-rashid commented on src/client/components/Footer/Footer.component.jsx
> +const Footer = ({}) => {
instead of writing ({}) just write ()..

2019-12-08 20:04 UTC, rakhshanda-rashid commented on src/client/components/Footer/Footer.component.jsx
> +          {""}
is there a special need to add curly brackets with inverted commas in <a> tag ..if you would just write HACK YOUR FUTURE and remove curly brackets before and after of it than it would worked ..

2019-12-14 11:09 UTC, bytewiz requested changes

2019-12-14 11:09 UTC, bytewiz commented on src/client/components/Footer/Footer.css
> +.Rectangle-btn {
lowercase this class name

2019-12-14 11:09 UTC, bytewiz commented on src/client/components/Footer/Footer.css
> +a{
rename this, don't use global tags this will mess up the styling, e.g. add a class name to wrap it

2019-12-18 09:51 UTC, adh86 commented
err

2019-12-18 09:54 UTC, adh86 commented
err

2019-12-18 11:14 UTC, closed without merging