endpoint to read annotation
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #92
Opened 2019-12-15 15:02 UTC by mo3ni

#36 Endpoint to read the annotation

2019-12-16 18:41 UTC, rakhshanda-rashid approved these changes
nice.work.. can successfully read the annotations.. also all conflicts fixed..

2019-12-16 23:11 UTC, JustinaOyov requested changes

2019-12-16 23:11 UTC, JustinaOyov commented on src/server/api/controllers/annotations.controller.js
> +      throw new error(`encorrect entry with the id of ${id}`, 404);
Nice work! Fetched screenshot annotations from DB using the updated Swagger. 
Just one small typo!
```suggestion
      throw new error(`incorrect entry with the id of ${id}`, 404);
```

2019-12-17 11:15 UTC, mo3ni commented on src/server/api/controllers/annotations.controller.js
> +      throw new error(`encorrect entry with the id of ${id}`, 404);
sorry I fixed it;

2019-12-17 11:47 UTC, JustinaOyov approved these changes

2019-12-17 11:51 UTC, zkwsk approved these changes

2019-12-17 11:52 UTC, merged