footer component
HackYourFuture-CPH/FP-annotatetheweb-class10 pull request #97
Opened 2019-12-17 13:15 UTC by adh86

2019-12-17 22:27 UTC, rakhshanda-rashid requested changes

2019-12-17 22:27 UTC, rakhshanda-rashid commented on src/client/components/footer/footer.component.js
> +      <div className="rectangle-btn"></div>
you have many things hardcoded in the Footer component ..it would be good practice to make it reuseable..

2019-12-18 18:15 UTC, adh86 commented on src/client/components/footer/footer.component.js
> +      <div className="rectangle-btn"></div>
what is suggestion for make it more flexible?

2019-12-19 10:01 UTC, rakhshanda-rashid commented on src/client/components/footer/footer.component.js
> +      <div className="rectangle-btn"></div>
for example: 
1. for <footer className="footer-btn"> instead of it you can use use props to pass 
<footer className={footerBtn}>
2. and pass it in the component too like this 
    const Footer = ({footerBtn})
3. and then in storybbok... in ur <Footer/> put 
<Footer footerBtn="footer-btn"/>

if u still not clear do tell me please

2019-12-20 11:17 UTC, laila1222 requested changes
When running storybook, I get an error that Footer.component is not found. 
Git is Not case sensitive by default, so even though you changed your files to Footer.component (from footer.component), git will still push it with  small case, like footer.component. We need to fix this problem. One way: 
1. in your (git) terminal write: git config core.ignorecase false      -> after this, when you change small case letters to capital, git will also push these changes. (??)

Otherwise, I had a few comments and suggestions. :)

2019-12-20 11:17 UTC, laila1222 commented on src/client/components/footer/footer.component.js
> +    <footer className="footer-btn">
By the classname footer-btn it seems like you are refering to some kind of button. But in fact, it is a footer. 
So I suggest you to change this classname to something else, like for example page-footer.

2019-12-20 11:17 UTC, laila1222 commented on src/client/components/footer/footer.component.js
> +      <div className="rectangle-btn"></div>
This is an empty div. 
You could use it like this (so the div would be wrapping the two links. Also, please change the "rectangle-btn" classname to something else, like for example footer-links-wrapper". 

```
<div className="footer-links-wrapper">
      <a href="https://www.hackyourfuture.dk" target="_blank">
        <img className="footer-hyf-logo" src={hyf_logo_black_background} />
      </a> 
      <a href="https://www.codeart.dk" target="_blank">
        <img className="footer-codeart-logo" src={codeart_logo_black_background}
        />
      </a>
      </div>
```
And you could give these css to this wrapper: 
`.footer-links-wrapper {
  width: 90%; /* This div will be 90% of parent (footer) element */
  margin: 0 auto; /*This will move the wrapper div into the center */
}`

2019-12-20 11:17 UTC, Laila1222 commented on src/client/components/footer/footer.css
> +  top: 1749px;
I know that these are the properties that we could see in Figma, but if we want to make a responsive page (and we have to), we will have to use some different properties. 
You could try the followings for this footer-btn: 
`position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   text-align: center;
   background: rgb(42, 42, 43);`
This is for a sample footer that I found on this  [W3School site](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_fixed_footer) , which works really well in this situation too.

2019-12-20 11:17 UTC, Laila1222 commented on src/client/components/footer/footer.css
> +  opacity: 1.6;
I know that these are the properties that we could see in Figma, but if we want to make a responsive page (and we have to), we will have to use some different properties.
I suggest to use the follwings: 
`.footer-hyf-logo {
  width: 15rem; /* This will set a responsive width */
  margin-right: 1rem;  /* This will give some space between the two pictures */
}`

2019-12-20 11:17 UTC, Laila1222 commented on src/client/components/footer/footer.css
> +  opacity: 1.6;
I know that these are the properties that we could see in Figma, but if we want to make a responsive page (and we have to), we will have to use some different properties.
I suggest to use the followings: 
`.footer-codeart-logo {
  width: 9rem;  /* This will set a responsive width */
  margin-left:1rem; /* This will give some space between the two pictures */
}`

2019-12-20 11:17 UTC, Laila1222 commented on src/client/components/footer/footer.css
> +  opacity: inherit;
If you follow my code suggestions, then you won't need this part at all. :)

2019-12-21 11:52 UTC, laila1222 requested changes
The code looks good, however  I'm still getting a build fail error due to case sensitivity regarding the file names. (If you see, here the footer files are called footer.component.js (lower case), but when you import something, it is with capital case like Footer.component.js. ) 
In git cd into src/client/components/footer
Then do the following three commands:
git mv -f footer.component.js Footer.component.js
git mv -f footer.css Footer.css
git mv -f footer.story.js Footer.story.js

Though, probably on your computer they are already called with capital letters, so you might need to change them back to lower case, like footer.component.js, footer.js, footer.story.js .
Then we must do the steps I wrote above in git, because if you just change the case in your editor, git wouldn't commit it, since the software is not case sensitive by deault. But if you change the name of the files in Git, then you will be able to commit and push the files with capital case.

2019-12-22 11:09 UTC, adh86 commented on src/client/components/footer/footer.component.js
> +    <footer className="footer-btn">
thanks for your review, I fixed it.

2019-12-22 13:01 UTC, bytewiz approved these changes

2019-12-22 14:29 UTC, merged